[build]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

  [deploy]
  startCommand = "node --enable-source-maps ./artifacts/api-server/dist/index.mjs"
  healthcheckPath = "/api/healthz"
  releaseCommand = "pnpm --filter @workspace/db run push"
  